on:
  workflow_dispatch:
    inputs:
      export_environment:
        type: boolean
        description: Export the build environment as tar artifact that can be imported with Docker.
  pull_request:
    branches:
      - 'main'
      - 'releases/*'

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # split out to make the llvm build optional for now
  setup_llvm:
    name: Load dependencies (llvm)
    uses: ./.github/workflows/dev_environment.yml
    with:
      dockerfile: build/devdeps.Dockerfile
      toolchain: llvm

  build_and_test_llvm:
    name: Build and test (llvm)
    needs: setup_llvm
    uses: ./.github/workflows/test_in_devenv.yml
    with:
      devdeps_cache: ${{ needs.setup_llvm.outputs.cache_key }}
      export_environment: ${{ github.event_name == 'workflow_dispatch' && inputs.export_environment }}

