on:
  issue_comment: # applies to PR and issue comments
    types: [created, edited]

name: Slash command dispatch

jobs:
  command_dispatch:
    name: Command dispatch
    runs-on: ubuntu-latest
    steps:
      - name: PR related commands
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
          issue-type: pull-request
          permission: write
          allow-edits: true
          dispatch-type: workflow
          commands: |
            testing
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}