on:
  issue_comment: # applies to PR and issue comments
    types: [created, edited]

name: Slash command dispatch

jobs:
  command_dispatch:
    name: Process slash commands
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        id: dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
          # The setting allow_edits means that edited comments can trigger a dispatch to that command.
          # This is only fine if the command does not edit comments in a way that would cause an infinite loop!
          config: >
            [
              {
                "command": "example",
                "issue_type": "pull-request",
                "dispatch_type": "repository",
                "permission": "write",
                "allow_edits": true
              },
              {
                "command": "create-cache",
                "issue_type": "pull-request",
                "dispatch_type": "workflow",
                "permission": "write",
                "allow_edits": true,
                "static_args": [
                  "repository=${{ github.repository }}",
                  "comment-id=${{ github.event.comment.id }}"
                ]
              },
              {
                "command": "create_cache",
                "event_type_suffix": "_command",
                "issue_type": "pull-request",
                "dispatch_type": "workflow",
                "permission": "write",
                "allow_edits": true,
                "static_args": [
                  "repository=${{ github.repository }}",
                  "comment-id=${{ github.event.comment.id }}"
                ]
              }
            ]

      - name: Edit comment with error message
        if: steps.dispatch.outputs.error-message
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ github.event.comment.body }}
  
            **Command Bot:** Could not process command.
            ```
            ${{ steps.dispatch.outputs.error-message }}
            ```
          # We replace the original comment to avoid an infinite loop
          edit-mode: replace
          reactions-edit-mode: replace
          reactions: |
          
      - name: Check whether to give a status report
        id: report
        run: |
          first_char=`echo "${{ github.event.comment.body }}" | head -n 1 | xargs -0 | cut -c 1`
          if [ "$first_char" == "/" ]; then
            echo "react=true" >> $GITHUB_OUTPUT
          fi

      - name: Indicate successful completion
        if: ${{ steps.reports.outputs.react == 'true' && ! steps.dispatch.outputs.error-message }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: hooray
