name: Slash Command Dispatch
on:
  issue_comment:
    types: [created, edited]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
          permission: write
          commands: |
            example
          allow-edits: true
