on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true

name: Dispatchable command

jobs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest

    outputs:
      json: "${{ steps.write.outputs.args }}"

    steps:
      - id: write
        run: |
          echo "args=$args" >> $GITHUB_OUTPUT
