on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      issue:
        required: true
        type: string
      pr:
        required: true
        type: string

name: Dispatchable command

jobs:
  dummy:
    name: Configure build
    runs-on: ubuntu-latest

    steps:
      - id: write
        run: |
          echo "args=$args" >> $GITHUB_OUTPUT

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v3
        with:
          repository: ${{ github.event.inputs.repository }}
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            Hello from GH ref ${{ github.ref_name  }}
            Issue: ${{ toJson(format('{0}', inputs.issue)) }}
            PR: ${{ toJson(format('{0}', inputs.pr)) }}
          edit-mode: replace
          reactions-edit-mode: replace
          reactions: |
