on:
  workflow_dispatch:

name: Dispatchable command

jobs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest

    outputs:
      json: "${{ steps.write.outputs.args }}"

    steps:
      - id: write
        run: |
          echo "args=$args" >> $GITHUB_OUTPUT
