name: example-command
on:
  repository_dispatch:
    types: [example-command]

jobs:
  example:
    if: ${{ github.event.client_payload.github.job == 'command_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v3
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            **Command Bot:** Processed `/${{ github.event.client_payload.slash_command.command }}` command. 
            GH ref: ${{ github.ref_name }}
            Source branch: ${{ github.event.client_payload.pull_request.head.ref }}
            Target branch: ${{ github.event.client_payload.pull_request.base.ref }}
            Better: ${{ github.event.client_payload.pull_request.number }}/merge

            Command name: ${{ github.event.client_payload.slash_command.command }}
            Command args: ${{ github.event.client_payload.slash_command.args.all }}
            
            Full context: 
            ```json
            ${{ toJson(github.event.client_payload) }}
            ```
          # We replace the original comment after processing it to avoid an infinite loop
          edit-mode: replace
          reactions-edit-mode: replace
          reactions: |
