name: example-command
on:
  repository_dispatch:
    types: [example-command]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        if: false
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.REPO_BOT_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            **Edit:** ${{ github.ref_name }}
          reactions: eyes
